[hugoVersion]
extended = false
min = "0.84.4"

[[mounts]]
source = "assets"
target = "assets"

[[mounts]]
source = "content"
target = "content"

[[mounts]]
source = "data"
target = "data"

[[mounts]]
source = "i18n"
target = "i18n"

[[mounts]]
source = "layouts"
target = "layouts"

[[mounts]]
source = "static"
target = "static"
