[hugoVersion]
extended = false
min = "0.84.4"

[[mounts]]
source = "assets/scss/_debugprint.scss"
target = "assets/scss/_debugprint.scss"

[[module.mounts]]
source = "assets/js/debug.js"
target = "assets/js/debug.js"

[[mounts]]
source = "data"
target = "data"

[[mounts]]
source = "content"
target = "content"

[[mounts]]
source = "i18n"
target = "i18n"

[[mounts]]
source = "layouts"
target = "layouts"

[[imports]]
path = "github.com/twbs/icons"
disable = false
ignoreConfig = true
ignoreImports = true

[[imports.mounts]]
source = "icons"
target = "assets/icons/bootstrap-icons"

[[imports]]
path = "github.com/tailwindlabs/heroicons"
disable = false
ignoreConfig = true
ignoreImports = true

[[imports.mounts]]
source = "optimized/outline"
target = "assets/icons/heroicons/24/outline"

[[imports.mounts]]
source = "optimized/solid"
target = "assets/icons/heroicons/24/solid"

[[imports]]
path = "github.com/tabler/tabler-icons"
disable = false
ignoreConfig = true
ignoreImports = true

[[imports.mounts]]
source = "src/_icons"
target = "assets/icons/tabler-icons"
