[hugoVersion]
extended = false
min = "0.84.4"

[[mounts]]
source = "assets/scss/_debugprint.scss"
target = "assets/scss/_debugprint.scss"

[[module.mounts]]
source = "assets/js/debug.js"
target = "assets/js/debug.js"

[[mounts]]
source = "data"
target = "data"

[[mounts]]
source = "content"
target = "content"

[[mounts]]
source = "i18n"
target = "i18n"

[[mounts]]
source = "layouts"
target = "layouts"
