[security]
mediatype = "text/plain"
path = "/.well-known/"
baseName = "security"
isPlainText = true
notAlternative = true

[dnblinklist]
baseName = 'links'
isPlainText = true
mediaType = 'application/json'
permalinkable = false
notAlternative = true
